# Generated by Django 4.2.6 on 2023-11-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='место выполнения')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='время выполнения')),
                ('action', models.CharField(max_length=500, verbose_name='действие')),
                ('good_habit', models.BooleanField(default=False, verbose_name='признак приятной привыки')),
                ('periodicity', models.SmallIntegerField(verbose_name='периодичность - (количество повторений в неделю)')),
                ('award', models.CharField(blank=True, max_length=100, null=True, verbose_name='награда')),
                ('limit_time', models.SmallIntegerField(verbose_name='продолжительность')),
                ('public', models.BooleanField(default=False, verbose_name='признак публичность')),
                ('habit_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связвнная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
